# defer

## 用法

### 1. 直接调用

参数值传递：

```go
func myFunc(srcFilePath string) {
 srcFile, err := os.Open(srcFilePath)
 if err != nil {
  return
 }
 defer srcFile.Close()  // 保证 srcFile 被正常关闭
}
```

### 2. 接匿名函数

闭包，会捕获和它处于同一作用域的其他变量。

```go
defer func() {
    // 需要在 return 后处理的操作
} ()
```

## 多个 defer 反序调用

一个函数中可以存在多个`defer`语句，这些`defer`语句的调用遵循先进后出的原则，即最后一个`defer`语句最先被执行。

```
func main() {
 defer fmt.Println("TOMO")
 defer fmt.Println("CAT")
 defer fmt.Println("TOMO-CAT")
 return
}

// 输出
TOMO-CAT
CAT
TOMO
```

## defer 在 return 后再执行

```go
var MyStr = "TOMO-CAT"

func testFunc() string {
 defer func() {
  MyStr = "CAT"
 }()
 fmt.Printf("testFunc::MyStr:[%s]\n", MyStr)
 return MyStr
}

func main() {
 newStr := testFunc()  // newStr 接受到的是 TOMO-CAT, 此时还未被 defer 函数修改为 CAT
 fmt.Printf("main::MyStr:[%s]\n", MyStr)
 fmt.Printf("main::newStr:[%s]\n", newStr)
 return
}

// 输出
testFunc::MyStr:[TOMO-CAT]
main::MyStr:[CAT]
main::newStr:[TOMO-CAT]
```

## panic 后的 defer 不可用

如果 panic 的位置在 defer 函数之后，那么 defer 函数可以捕获 panic：

```go
package main

import "fmt"

func main() {
 defer func() {
  if err := recover(); err != nil {
   fmt.Printf("panic, err:%v\n", err)
  }
 }()
 
 var pi *int = nil
 fmt.Println(*pi)
 
 return
}

// 输出:
panic, err:runtime error: invalid memory address or nil pointer dereference
```

如果 panic 的位置在 defer 函数之前，那么该 panic 无法被 defer 函数捕获：

```go
package main

import "fmt"

func main() {
 var pi *int = nil
 fmt.Println(*pi)
 
 defer func() {
  if err := recover(); err != nil {
   fmt.Printf("panic, err:%v\n", err)
  }
 }()
 
 return
}

// 输出:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48eac1]

goroutine 1 [running]:
main.main()
 /box/main.go:7 +0x31

Exited with error status 2
```
