# 析构函数中为什么不能抛出异常

## 答案

从语法上来说，析构函数可以抛出异常。

但从逻辑上和风险控制上，析构函数中不要抛出异常，因为栈展开容易导致 **资源泄露** 和 **程序崩溃**，所以别让异常逃离析构函数。

## 解析

析构函数从语法上是可以抛出异常的，但是这样做很危险，请尽量不要这要做。原因在《More Effective C++》中提到两个：

* 如果析构函数抛出异常，则异常点之后的程序不会执行，如果析构函数在异常点之后执行了某些必要的动作比如释放某些资源，则这些动作不会执行，会造成诸如资源泄漏的问题。
* 通常异常发生时，c++ 的异常处理机制在异常的传播过程中会进行栈展开（stack-unwinding），因发生异常而逐步退出复合语句和函数定义的过程，被称为栈展开。在栈展开的过程中就会调用已经在栈构造好的对象的析构函数来释放资源，此时若其他析构函数本身也抛出异常，则前一个异常尚未处理，又有新的异常，会造成程序崩溃。

## Reference

[1] <https://blog.csdn.net/K346K346/article/details/55214384>
